# Generated by Django 5.2 on 2025-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="intruder_image/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
